[package]
name = "mystdapp"
version = "0.1.0"
authors = ["Automata Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
important = { path = "../important" }